### ISSUE TITLE
Minor issues for first public outing of OBO

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/owned-by-oxford-project#1]
- [x] Choose name of the page, as appears in the webpage tab.
- [x] Choose style of map tiles used. See https://www.thunderforest.com/ for options.
- [x] Choose Primary filter category. There isn't one chosen ATM, so they are all lumped into All Entries. Not very satisfactory. There will inevitably always be some initiatives that can't be categorised base on a filter choice.
- [x] Decide how we approach categorising the uncategorised?
- [x] There is very little data displayed for each entity. What are priority fields to add? (See also #4)
- [x] Add GFO data (see #7)
- [x] Add Covid Mutual Aid 
- [ ] Put sensible text in the about/info box. (Needs unhardwiring the new internationalised about page. See https://github.com/SolidarityEconomyAssociation/sea-map/issues/125)
- [x] Having the panel closed when the map page loads.
- [ ] <del>Change the colour of the panel open/close tab to ? </del>

**Comment by wu-lee** [comment]
>     * Choose style of map tiles used

How do we choose? Or has someone at ObO chosen?

**Comment by wu-lee** [comment]
I've added the covid-mutual-aid dataset, filtered with:

    FILTER(REGEX(UCASE(?street), 'OX[0-9]{1,2}\\b'))

This attempts to limit the query to addresses which seem to have an oxford postcode, although the data does not have an explicit postcode field so it's a bit fuzzy, and may miss  out some Oxford-located initiatives if they don't include a postcode.

**Comment by ColmMassey** [comment]
You may have broken it in the process!

**Comment by wu-lee** [comment]
Yes, I did, I rediscovered a limitation of sea-map which breaks it when deployed at a path other than top level (i.e. like `/owned-by-oxford/`) and my hack I worked around it with last time I deployed it.  Attempting to fix it properly I ran out of time, and had to go. Going to make another attempt shortly.

**Comment by wu-lee** [comment]
Ok, fixed that sea-map problem, so its back up again!

**Comment by ColmMassey** [comment]
> 
> 
> > ```
> > * Choose style of map tiles used
> > ```
> 
> How do we choose? Or has someone at ObO chosen?

It's in their court. Not urgent for anyone, so we can leave it for now.

**Comment by wu-lee** [comment]
Ok, I've added an open-data conversion for good-food-oxford (still manual currently), and added the dataset to the ObO site. It's deployed and should be visible.

I use the Location Id as the prirmary identifier, and merely capture (but ignore) the Organisation Id.

There's no usable description field, unfortunately.

**Comment by wu-lee** [comment]
Also the covid-mutual-aid data is added now too.

**Comment by wu-lee** [comment]
See #3, short postcode now being used for the directory.

**Comment by ColmMassey** [comment]
> See #3, short postcode now being used for the directory.

Great. Works well. Would it be hard to extend to also do very short? i.e. 3 digits?

**Comment by wu-lee** [comment]
>  Would it be hard to extend to also do very short? i.e. 3 digits?

Not sure I understand exactly - isn't OX10 shorter than 3 digits? Or do you mean 3 characters? That would however conflate OX1 and OX10 to OX19, is that useful?

However, in general, this is a hard-wired alteration of the list of fields in the sea-map code - although not a major change, it is probably rather too specific in the general case and warrants being moved out to site-specific customisation rather than being core. (Which we can't do yet but I think we should.)

**Comment by wu-lee** [comment]
>     * Having the panel closed when the map page loads.

I've set the `defaultOpenSidebar` option to `false` in the ObO map config. Unfortunately there's a bug which makes it open anyway. Fortunately, I think I fixed that (hopefully without introducing new sidebar opening bugs in less obvious cases).  Anyway, it doesn't open by default now in ObO. 

See also https://github.com/SolidarityEconomyAssociation/sea-map/issues/131#issuecomment-972832184

**Comment by wu-lee** [comment]
>     * Put sensible text in the about/info box. (Needs unhardwiring the new internationalised about page

This may be nearly fixed as per https://github.com/SolidarityEconomyAssociation/sea-map/issues/125#issuecomment-971588929 - but if not, some sensible text (plus translations?) is needed.

**Comment by ColmMassey** [comment]
> 
> 
> > Would it be hard to extend to also do very short? i.e. 3 digits?
> 
> Not sure I understand exactly - isn't OX10 shorter than 3 digits? Or do you mean 3 characters? That would however conflate OX1 and OX10 to OX19, is that useful?
> 
> However, in general, this is a hard-wired alteration of the list of fields in the sea-map code - although not a major change, it is probably rather too specific in the general case and warrants being moved out to site-specific customisation rather than being core. (Which we can't do yet but I think we should.)

I have confused you. But independently you addressed my request and we can search for OX1, OX2

**Comment by ColmMassey** [comment]
>     * Decide how we approach categorising the uncategorised?

Is this still relevant as we are now using postcodes?

**Comment by wu-lee** [comment]
> Is this still relevant as we are now using postcodes?

Suspect it isn't, if postcodes are sufficient.

**Comment by ColmMassey** [comment]
We have made the decision to make 2 sea-map instances for the OBO project. The current one will remain for the planners and steering committee etc, and provide access to as much relevant info as possible. We now need a second one, which will be cleaner and be the one for public consumption. I'll create a new ticket for that one and specify what it needs there. 
https://github.com/SolidarityEconomyAssociation/owned-by-oxford-project/issues/8

**Comment by ColmMassey** [comment]
We can keep this one open for the moment for any discussions on what still needs finishing on the non public map.

**Comment by ColmMassey** [comment]
@wu-lee can you swithch obo-public to use Primary Activity as the Directory filter?

**Comment by ColmMassey** [comment]
> @wu-lee can you swithch obo-public to use Primary Activity as the Directory filter?

Is there anything holding this back?

**Comment by wu-lee** [comment]
Only that my focus was elsewhere. I've redeployed with the primary activity as directory filter just now.
