### ISSUE TITLE
OBO Filter and Search Improvements

### ISSUE THREAD

**Issue by ColmDC** [SolidarityEconomyAssociation/owned-by-oxford-project#22]
The funded part of the OBO project finished at the end of 2022. The following Usabilty needs came from and end of year feedback session with OBO OP Team.

We need to break the following into Issues and see if we can scehdule them under other budgets, as they are likley to benefit more than just the OBO project/ 

Usability need 1: there are two categories of people who will visit the site,
represented by the "Type for map" field, who will primarily be interested in one
or other of these types of organisation.

- Currently there's no way to distinguish these on the map, but we can include
the "Type for map" field as a drop-down search filter as a first step.
- To do this we need a name for it which will make sense to visiting users -
Anna and Simon will try to come up with something.
- This arrangement is still possibly a bit unintuitive, however. Users need to
know the filter exists and go and set it.
- As an alternative, Nick suggested we could publish two maps, each showing one
of these two categories, with no filter then required if you have selected the
right map.
- Anna thought this might work better.
- These distinct maps could be implemented as a later step, as slightly more
work than adding the filter. Probably the original would stay, and show one
category, and a new one added for the latter.

Usability need 2: the directory and the drop-down filters currently can only
filter by "primary activity". And then, even if an "activities" filter were
added, these work separately and are combined by intersection. This makes a
search amongst all organisations for membership of a given category (e.g.
"food") hard or impossible.

- This need suggests we need to combine the "primary activity" and "activities"
fields into one, multi-valued field.
- We would then need to display this as the directory, and possibly as a filter
too. These would permit the same filtering function, approximately, but in
different ways.
- However, mykomap does not currently support a multi-valued field as a filter,
- And possibly not as the directory either (need to check this).
- This would also need altering the Airtable columns, and therefore the data
factory.
- Some extra logic would also be needed in the data factory to combine "primary
activities" and "activities" from the "external initiatives" table.
- If not implemented, this work would need to be scheduled within DCC's other
priorities

Usability need 3: the text search only searches by name, so if you search for
"food" you don't find all the food providers, just those with "food" in their name
- Ideally this would search for the name and the activities too.
- (Possibly also other fields? This wasn't discussed however.)
- We can add the "primary activity"/"activities" fields to the search index.
- However, we may need to check that mykomaps allows searching multiple-valued
vocabulary fields (like activities)
- If not implemented, this work would need to be scheduled within DCC's other
priorities

Very Quick Items
- [X] Hide the database panel;
- [x] Omit "Relationship" field.
- [x] if we don't have time to add more filter options than Activities, let's exclude the filter from the search panel until there is more than 1 in there.
- [x] Can usabilty need 3 not be addressed with different config options? Can we not set primaryActivity as a search field?

**Comment by ColmDC** [comment]
@wu-lee can you look at the 4 tick boxes at the bottom of the Epic description. Can you comment if you think they are trivial changes that can be made?

**Comment by wu-lee** [comment]
Suggestion from meeting of 10/2/23
- Preserve primary and secondary activities in the data in addition to the merged field
- Show primary/secondary in the pop up dialogs and filter, but the unified activities in the directory
- Add org structure as a search filter

**Comment by ColmDC** [comment]
THere is a bug in the search code, where text searches don't match with labels of fields that have been spefied to be searched in the config, or commandline.

**Comment by wu-lee** [comment]
Itemising the various suggestions from here and from the summarising email to Anna/Colm (attached), excluding those already itemised above.
- [x] Anna/Simon provide us for a user-friendly name for "Type for map" field, then:
  - [x] Include this field in the data-factory's output data 
  - [x] Show this field in the ObO map
  - [ ] add it to the drop-down filters 
  - Given the above, later:
    - [ ] ~~Publish two maps instead of a single one, each showing data with one or other of the "Type for map" fields~~
- [x] Switch ObO to v3 of MykoMap and use the custom field / sparql bypass support there (currently on a hacked  sparql bypass branch of Mykomap for ObO)
- [x] Preserve primary and secondary activities in the data, but add a merged field combining them
- [x] Check that a vocab field can be used for the map directory panel *ANSWER: no, if used, vocab IDs are shown*
  - [x] and implement if not
  - [x] Check that multi-value field can be used for the map directory panel *ANSWER: no, multiple values seem to be stringified into a single value*
    - [x] and implement if not
    - [x] show the combined activities field in the directory.
- [x] Check that a vocab field can be included as a search filter *ANSWER: no, the ID is indexed for search, not the value*
  - [x] and implement if not
- [x] Check that a multi-value field can be included as a search filter  *ANSWER: no, a multiple-value field seems to be omitted from the search filters even when configured to be included*
  - [x] and implement if not
  - [x] Show primary/secondary activity in the pop up dialogs and as a search filter
  - [x] Show organisational structure to the pop-up dialogs, and as a search filter
- [x] Check that a multi-value field can be included in the text search *ANSWER: not properly, multiple values seem to be stringified into a single value, with a comma delimiter* 
  - [x] and implement if not
  - [x] Add the combined activities field to the text search
  - [x] Add the organisational structure field to the text search


Note that not all of these are to be done immediately, but they're included here to clarify the jobs arising from this discussion and allow them to be prioritised. They may warrant becoming separate tickets.
[Re: Map update questions - 2022-12-08 1042.txt](https://github.com/DigitalCommons/owned-by-oxford-project/files/10511126/Re.Map.update.questions.-.Nick.Stokoe.nick%40noodlefactory.co.uk.-.2022-12-08.1042.txt)

**Comment by ColmDC** [comment]
Taking a look at 
https://dev.maps.solidarityeconomy.coop/temp/

Should a text search with the word spaces identify all the orgs with Community and Collective Spaces as an Activty?

**Comment by ColmDC** [comment]
Moving bugs you've already identified after completing the TypeScript port here...

 - ~~clearfilters button doesn't~~
 - ~~back buttons broken?~~
 - ~~"clearFilter" phrase and other language things not set~~
 - ~~setting filter then unsetting it doesn't work - until you set to another value?~~
 -  ~~Countries (on ICA not OBO) includes "All" and "Any"~~
 - ~~clicking on initiatives in sidebar won't popup when they are grouped?~~
 - ~~clicking on initiatives in sidebar won't dialog? (last two may have been fixed magically)~~

**Comment by ColmDC** [comment]
It is hard to test with these known bugs in place. Let's address these first before doing any more involved testing.

**Comment by ColmDC** [comment]
I have attached the 3 bugs to this Epic. Do you think that once they are addressed we will be able to close this Epic? 

Do we have a clear idea how the Type for map (with better title) would be configured to support easy distinguishing between those types within the filer/directory setting (not markers/icons)?

**Comment by wu-lee** [comment]
For ObO, I think we need a way to show localised field names. I don't think we have an issue for that however. Will create that.

Also, I need to check that the text search works on vocab fields.

**Comment by ColmDC** [comment]
>Countries (on ICA not OBO) includes "All" and "Any"
This is not an OBO issue. Is it duplicated in another ticket?
Covered here I beleive https://github.com/DigitalCommons/mykomap/issues/177

**Comment by ColmDC** [comment]
I feel we can close this Epic. We knonw that supporting adhoc vocads in the filters is needed to fully support this, but lets create a new epic when Zenhub allows us, to handle the next steps of improving the directory and search panels.
